import React from 'react';
import {AbsoluteFill, interpolate} from 'remotion';

const P={bg:'#090b10',panel:'#151a22',line:'#46505d',paper:'#f0ece2',muted:'#9ea6b4',gold:'#e2b35c',red:'#d55f5f',blue:'#76a8c9',green:'#72a47e',violet:'#9a83ba'};
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const mix=(p:number,a:number,b:number)=>interpolate(p,[0,1],[a,b],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});

const Grain=()=> <AbsoluteFill style={{opacity:.055,backgroundImage:'radial-gradient(circle,#fff 0 1px,transparent 1px)',backgroundSize:'22px 22px'}}/>;
const Label=({x,y,text,size=44,color=P.paper}:{x:number;y:number;text:string;size?:number;color?:string})=> <div style={{position:'absolute',left:x,top:y,fontSize:size,fontWeight:800,color,letterSpacing:1.2,textShadow:'0 3px 18px #000',whiteSpace:'pre-line'}}>{text}</div>;
const Box=({x,y,w,h,text,accent=false}:{x:number;y:number;w:number;h:number;text:string;accent?:boolean})=> <div style={{position:'absolute',left:x,top:y,width:w,height:h,border:`2px solid ${accent?P.gold:P.line}`,background:accent?'#211b12':P.panel,display:'flex',alignItems:'center',justifyContent:'center',fontSize:30,fontWeight:800,color:accent?P.gold:P.paper,textAlign:'center',padding:18,boxSizing:'border-box',whiteSpace:'pre-line'}}>{text}</div>;
const Person=({x,y,s=1,child=false}:{x:number;y:number;s?:number;child?:boolean})=>{const head=child?34:46;const body=child?50:72;return <div style={{position:'absolute',left:x,top:y,transform:`scale(${s})`,transformOrigin:'50% 100%'}}><div style={{position:'absolute',left:-head/2,top:-body-head,width:head,height:head,borderRadius:'50%',background:'#d8b49e'}}/><div style={{position:'absolute',left:-16,top:-body,width:32,height:body*.62,borderRadius:8,background:child?P.blue:'#3a424e'}}/><div style={{position:'absolute',left:-10,top:-body*.4,width:8,height:body*.45,background:'#252b34'}}/><div style={{position:'absolute',left:2,top:-body*.4,width:8,height:body*.45,background:'#252b34'}}/></div>};

const Apartment=({visual,p}:{visual:string;p:number})=>{
  if(visual==='storage-joke') return <AbsoluteFill style={{background:'linear-gradient(180deg,#11151c,#07090d)'}}><Label x={180} y={150} text="収納は、あります。" size={68}/><Label x={180} y={245} text="余裕は、ありません。" size={68} color={P.gold}/><div style={{position:'absolute',right:220,top:180,width:560,height:650,border:`5px solid ${P.line}`,display:'grid',gridTemplateColumns:'1fr 1fr',gridTemplateRows:'repeat(4,1fr)',gap:10,padding:18,boxSizing:'border-box'}}>{Array.from({length:8}).map((_,i)=><div key={i} style={{background:i%2?'#222936':'#181e27',border:'1px solid #39424e',opacity:clamp(p*2-i*.08),transform:`translateY(${(1-p)*30}px)`}}/>)}</div><Grain/></AbsoluteFill>;
  const end=visual==='return-room'||visual==='final-room-dark';
  return <AbsoluteFill style={{background:end?'linear-gradient(180deg,#0c0f14,#050608)':'linear-gradient(180deg,#161b23,#090b10)'}}><div style={{position:'absolute',left:120,top:160,width:1680,height:650,border:`2px solid ${P.line}`,background:'#10151c'}}/><div style={{position:'absolute',left:1160,top:245,width:390,height:565,border:`7px solid ${P.line}`,background:'#202731'}}><div style={{position:'absolute',inset:0,background:'#2d3540',transformOrigin:'0 50%',transform:`perspective(700px) rotateY(${-68*clamp(p*2)}deg)`}}/></div><Person x={690} y={810} s={1.35}/><Person x={840} y={810} s={1.38}/>{!end&&<Person x={1040} y={810} s={1.22}/>} {visual==='child-room'&&<><Label x={1200} y={130} text="5畳" size={92}/><Label x={1180} y={225} text="将来の子ども部屋" size={34} color={P.muted}/></>}{visual==='apartment-tour'&&<Label x={145} y={95} text="SUNDAY 10:47 / MODEL ROOM" size={26} color={P.muted}/>} {visual==='return-room'&&<Label x={170} y={145} text="あの5畳へ戻る" size={62}/>}<Grain/></AbsoluteFill>;
};

const CostScene=({visual,p}:{visual:string;p:number})=>{
  if(visual==='cost-cloud'){
    const items=['保育園','食費','服','習い事','学校','塾','大学','住宅ローン','育休','時短勤務','病院','PTA'];
    return <AbsoluteFill style={{background:P.bg}}><Box x={740} y={260} w={440} h={500} text="5畳" accent/>{items.map((t,i)=>{const a=(i/items.length)*Math.PI*2;const r=340+(i%2)*70;const x=960+Math.cos(a)*r-90;const y=505+Math.sin(a)*r-34;return <div key={t} style={{position:'absolute',left:x,top:y,width:180,height:68,border:`1px solid ${P.line}`,background:P.panel,color:i%4===0?P.gold:P.paper,fontSize:24,fontWeight:800,display:'flex',alignItems:'center',justifyContent:'center',opacity:clamp(p*2-i*.05),transform:`translateY(${(1-p)*45}px)`}}>{t}</div>})}<Grain/></AbsoluteFill>;
  }
  const search=visual==='search-cost';
  return <AbsoluteFill style={{background:'linear-gradient(180deg,#121720,#07090c)'}}><div style={{position:'absolute',left:240,top:700,width:1440,height:18,background:'#544235'}}/><div style={{position:'absolute',left:600,top:190,width:820,height:500,border:'8px solid #3b4350',borderRadius:18,background:'#202631'}}><div style={{position:'absolute',inset:24,background:'#efebe1',color:'#111318',padding:38,boxSizing:'border-box'}}>{search?<><div style={{height:62,border:'2px solid #b7b2a8',borderRadius:32,padding:'11px 24px',fontSize:28}}>子ども　一人　費用</div>{['教育費はいくら？','大学までの総額','子育てに必要なお金','住宅費と家族'].map((t,i)=><div key={t} style={{fontSize:24,marginTop:32,opacity:clamp(p*2-i*.15)}}>{t}</div>)}</>:<><div style={{fontSize:66,fontWeight:900}}>EXCEL</div><div style={{marginTop:42,display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:4}}>{Array.from({length:25}).map((_,i)=><div key={i} style={{height:34,border:'1px solid #c0bbb2',background:i%6===0?'#e7d095':'#fff'}}/>)}</div><div style={{fontSize:36,fontWeight:900,marginTop:32}}>35億年 → 表計算</div></>}</div></div><Person x={470} y={810} s={1.4}/><Grain/></AbsoluteFill>;
};

const Paradox=({visual,p}:{visual:string;p:number})=>{
  if(visual==='title-question') return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 45%,#28212b,#090b10 68%)',alignItems:'center',justifyContent:'center'}}><div style={{fontSize:82,fontWeight:900,lineHeight:1.35,textAlign:'center',color:P.paper,transform:`scale(${mix(clamp(p*1.5),.92,1)})`}}>なぜ豊かな国にとって<br/><span style={{color:P.gold}}>子どもは「贅沢品」</span>になったのか？</div><Grain/></AbsoluteFill>;
  return <AbsoluteFill style={{background:P.bg}}><div style={{position:'absolute',left:180,top:190,width:700,height:590,border:`2px solid ${P.line}`,background:'#12161c'}}><Label x={150} y={55} text="貧しい時代" size={44}/>{Array.from({length:8}).map((_,i)=><Person key={i} x={120+(i%4)*150} y={300+Math.floor(i/4)*190} s={.78} child={i>1}/>)}</div><div style={{position:'absolute',right:180,top:190,width:700,height:590,border:`2px solid ${P.line}`,background:'#16191f'}}><Label x={150} y={55} text="豊かな時代" size={44}/><Person x={250} y={500} s={1.0}/><Person x={390} y={500} s={1.0}/><Person x={530} y={500} s={.85} child/></div><Label x={900} y={410} text="≠" size={110} color={P.red}/><Grain/></AbsoluteFill>;
};

const DataScene=({visual,p}:{visual:string;p:number})=>{
  if(visual==='appliance-parade') {const items=['エアコン','洗濯機','冷蔵庫','掃除機','通販','紙おむつ'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={100} text="便利さは増えた" size={62}/>{items.map((t,i)=><Box key={t} x={170+i*275} y={320+(i%2)*130} w={230} h={220} text={t} accent={i===5}/>) }<Label x={1110} y={790} text="なのに、子どもは減った。" size={50} color={P.gold}/><Grain/></AbsoluteFill>}
  if(visual==='money-explanation'||visual==='price-transformation') {const items=['住宅費','教育費','雇用不安','将来不安'];return <AbsoluteFill style={{background:P.bg}}><div style={{position:'absolute',left:260,top:260,width:500,height:500,borderRadius:'50%',border:`4px solid ${P.line}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:140,color:P.paper}}>¥</div>{items.map((t,i)=><Box key={t} x={980+(i%2)*360} y={260+Math.floor(i/2)*230} w={300} h={170} text={t}/>) }{visual==='price-transformation'&&<Label x={780} y={120} text="問題は財布だけではない" size={58} color={P.gold}/>}<Grain/></AbsoluteFill>}
  const fertility=visual==='fertility-chart';const vals=fertility?[3.3,2.8,2.2,1.8,1.6,1.5]:[35,52,67,81,93];
  return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={90} text={fertility?'OECD / 合計特殊出生率':'60年間の豊かさ'} size={54}/><div style={{position:'absolute',left:190,top:230,width:1500,height:570,borderLeft:`3px solid ${P.line}`,borderBottom:`3px solid ${P.line}`}}>{vals.map((v,i)=>{const h=fertility?(v/3.6)*470:(v/100)*470;return <div key={i} style={{position:'absolute',left:90+i*(1320/(vals.length-1)),bottom:0,width:46,height:h*p,background:i===vals.length-1?P.red:P.gold}}><div style={{position:'absolute',top:-42,left:-12,color:P.paper,fontSize:26}}>{fertility?v.toFixed(1):v}</div></div>})}</div><Grain/></AbsoluteFill>;
};

const Becker=({visual,p}:{visual:string;p:number})=>{
  if(visual==='becker-portrait') return <AbsoluteFill style={{background:P.bg}}><div style={{position:'absolute',left:250,top:170,width:500,height:620,border:`4px solid ${P.line}`,background:'linear-gradient(150deg,#28303b,#12161c)'}}><div style={{position:'absolute',left:140,top:90,width:220,height:220,borderRadius:'50%',background:'#c8b6a0'}}/><div style={{position:'absolute',left:110,top:330,width:280,height:230,borderRadius:'120px 120px 20px 20px',background:'#3b4450'}}/></div><Label x={870} y={255} text="GARY BECKER" size={74}/><Label x={870} y={365} text="子どもを、経済学で見る。" size={48} color={P.gold}/><Grain/></AbsoluteFill>;
  if(visual==='resource-pie') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={100} text="親の資源は有限" size={62}/>{['お金','時間','労力'].map((t,i)=><div key={t} style={{position:'absolute',left:360+i*450,top:360,width:300,height:300,borderRadius:'50%',background:[P.gold,P.blue,P.violet][i],opacity:.8,display:'flex',alignItems:'center',justifyContent:'center',fontSize:46,fontWeight:900,color:'#111318',transform:`scale(${mix(clamp(p*2-i*.12),.2,1)})`}}>{t}</div>)}<Grain/></AbsoluteFill>;
  if(visual==='quantity-quality') return <AbsoluteFill style={{background:P.bg}}><div style={{position:'absolute',left:160,top:230,width:680,height:520,border:`2px solid ${P.line}`}}><Label x={250} y={50} text="人数" size={52}/>{Array.from({length:6}).map((_,i)=><Person key={i} x={120+(i%3)*190} y={290+Math.floor(i/3)*175} s={.78} child/>)}</div><div style={{position:'absolute',right:160,top:230,width:680,height:520,border:`2px solid ${P.line}`}}><Label x={170} y={50} text="一人への投資" size={52}/><Person x={340} y={430} s={1.25} child/><Label x={70} y={240} text="教育　体験　住環境　安全" size={30} color={P.muted}/></div><Label x={895} y={420} text="⇄" size={100} color={P.gold}/><Grain/></AbsoluteFill>;
  const items=['家','教育','服','習い事','大学','旅行','安全','体験'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={95} text="一人あたりの投資額が膨らむ" size={58}/>{items.map((t,i)=><Box key={t} x={190+(i%4)*400} y={250+Math.floor(i/4)*280} w={320} h={190} text={t} accent={i%3===0}/>) }<Grain/></AbsoluteFill>;
};

const Car=({p}:{p:number})=> <AbsoluteFill style={{background:P.bg}}><Label x={160} y={100} text="所得が2倍 → 台数も2倍？" size={62}/><div style={{position:'absolute',left:230,top:460,width:460,height:160,borderRadius:'80px 120px 35px 35px',background:'#596674'}}/><div style={{position:'absolute',left:1030,top:400,width:650,height:210,borderRadius:'130px 180px 40px 40px',background:'linear-gradient(90deg,#9d7439,#d9bd70)',transform:`translateX(${(1-p)*150}px)`}}/><Label x={1130} y={660} text="より高品質な一台" size={38} color={P.gold}/><Grain/></AbsoluteFill>;

const Parenting=({visual,p}:{visual:string;p:number})=>{
  if(visual==='cafe-friend'||visual==='everyone-does-it') return <AbsoluteFill style={{background:'linear-gradient(180deg,#17131a,#090b10)'}}><div style={{position:'absolute',left:220,top:650,width:1480,height:24,background:'#58453b'}}/><Person x={610} y={650} s={1.35}/><Person x={1260} y={650} s={1.35}/><div style={{position:'absolute',left:1080,top:400,width:180,height:270,border:'5px solid #56606d',borderRadius:28,background:'#202631',transform:`rotate(${mix(p,-10,3)}deg)`}}><div style={{position:'absolute',inset:18,background:'#ddd8cd',color:'#111318',padding:15,fontSize:21}}>プログラミング<br/>6歳クラス</div></div>{visual==='everyone-does-it'&&<Label x={500} y={145} text="『みんなやってるから』" size={74} color={P.gold}/>}<Grain/></AbsoluteFill>;
  if(visual==='parent-arms-race'||visual==='six-year-old-exam') {const labels=['英語','塾','スポーツ','プログラミング','海外体験'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={85} text={visual==='six-year-old-exam'?'誰も宣戦布告していない':'子育ての静かな軍拡競争'} size={58}/>{labels.map((t,i)=><div key={t} style={{position:'absolute',left:180+i*325,top:650-(i+1)*68,width:270,height:130+(i+1)*70,border:`2px solid ${P.line}`,background:P.panel,display:'flex',alignItems:'center',justifyContent:'center',fontSize:32,color:i===4?P.gold:P.paper}}>{t}</div>)}{visual==='six-year-old-exam'&&<Box x={710} y={760} w={500} h={110} text="英検　受験票　6歳" accent/>}<Grain/></AbsoluteFill>}
  if(visual==='intensive-parenting'||visual==='bar-raised') {const labels=['時間','お金','注意','知識'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={90} text={visual==='bar-raised'?'「良い親」の最低ライン':'集中的子育て'} size={60}/>{labels.map((t,i)=><div key={t} style={{position:'absolute',left:220+i*390,top:300,width:300,height:380,background:[P.gold,P.blue,P.violet,P.green][i],opacity:.7,transform:`scaleY(${mix(clamp(p*2-i*.1),.15,1)})`,transformOrigin:'50% 100%',display:'flex',alignItems:'flex-end',justifyContent:'center',paddingBottom:30,fontSize:34,fontWeight:900,color:'#111318'}}>{t}</div>)}<Grain/></AbsoluteFill>}
  const roles=['健康','教育','自己肯定感','英語','スポーツ','SNS','金融教育','体験'];return <AbsoluteFill style={{background:P.bg}}><Person x={960} y={600} s={1.6}/>{roles.map((t,i)=>{const a=-Math.PI/2+(i/roles.length)*Math.PI*2;const x=960+Math.cos(a)*340-90;const y=500+Math.sin(a)*300-36;return <Box key={t} x={x} y={y} w={180} h={72} text={t} accent={i%4===0}/>})}{visual==='corporate-parent'&&<Label x={145} y={90} text="親株式会社 / 兼任役職：多すぎ" size={56}/>}<Grain/></AbsoluteFill>;
};

const Office=({visual,p}:{visual:string;p:number})=>{
  if(visual==='career-ladder') return <AbsoluteFill style={{background:P.bg}}><Person x={560} y={790} s={1.5}/>{Array.from({length:7}).map((_,i)=><div key={i} style={{position:'absolute',left:790+i*130,top:720-i*85,width:150,height:30,background:i<5?P.blue:'#39414c'}}/>)}<Label x={1100} y={140} text="昇進" size={78} color={P.gold}/><Grain/></AbsoluteFill>;
  if(visual==='opportunity-cost'||visual==='full-life') return <AbsoluteFill style={{background:P.bg}}><Box x={180} y={260} w={680} h={470} text="子ども" accent/><Box x={1060} y={220} w={680} h={550} text={'キャリア\n時間\n自由\n旅行\n趣味'}/><Label x={900} y={430} text="VS" size={86} color={P.red}/><Grain/></AbsoluteFill>;
  if(visual==='child-penalty') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={90} text="第一子誕生後" size={58}/><div style={{position:'absolute',left:200,top:250,width:1500,height:520,borderLeft:`2px solid ${P.line}`,borderBottom:`2px solid ${P.line}`}}><svg width="1500" height="520"><polyline points="0,260 300,240 650,220 1000,200 1420,180" fill="none" stroke={P.blue} strokeWidth="8"/><polyline points={`0,260 300,250 650,${250+100*p} 1000,${265+135*p} 1420,${280+160*p}`} fill="none" stroke={P.red} strokeWidth="8"/></svg><Label x={1240} y={100} text="男性" size={32}/><Label x={1240} y={360} text="女性" size={32}/></div><Grain/></AbsoluteFill>;
  if(visual==='nursery-call') return <AbsoluteFill style={{background:'linear-gradient(90deg,#111820 0 62%,#191210 62%)'}}><div style={{position:'absolute',left:180,top:230,width:850,height:500,border:`2px solid ${P.line}`}}>{Array.from({length:6}).map((_,i)=><div key={i} style={{position:'absolute',left:80+(i%3)*240,top:80+Math.floor(i/3)*190,width:180,height:90,background:'#1c2430',border:`1px solid ${P.line}`}}/>)}<Person x={420} y={630} s={1.2}/></div><div style={{position:'absolute',right:240,top:270,width:480,height:340,border:'6px solid #56606d',borderRadius:42,background:'#202631'}}><Label x={120} y={70} text="保育園" size={52}/><Label x={205} y={185} text="☎" size={90} color={P.red}/></div><Grain/></AbsoluteFill>;
  return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={85} text={visual==='capitalism-joke'?'保育園は資本主義の下請けではない':'時間という最も高い通貨'} size={56}/><div style={{position:'absolute',left:170,top:240,width:1580,height:550,border:`2px solid ${P.line}`,display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:12,padding:24,boxSizing:'border-box'}}>{Array.from({length:15}).map((_,i)=><div key={i} style={{background:'#151b23',border:'1px solid #343d49'}}><div style={{height:18,width:`${45+(i%5)*10}%`,margin:18,background:i%4===0?P.gold:'#56606e'}}/></div>)}</div><Person x={520} y={790} s={1.35}/><Grain/></AbsoluteFill>;
};

const Life=({visual,p}:{visual:string;p:number})=>{const opts=['結婚','子ども','転職','海外','大学院','起業','推し活','犬','一人暮らし','旅行','趣味','キャリア'];if(visual==='tetris-life') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={90} text="すでに満杯の人生" size={60}/><div style={{position:'absolute',left:560,top:180,width:800,height:650,border:`5px solid ${P.line}`,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gridAutoRows:'125px',gap:9,padding:14,boxSizing:'border-box'}}>{opts.map((t,i)=><div key={t} style={{background:[P.blue,P.violet,P.green,P.gold][i%4],opacity:.7,color:'#111318',fontSize:24,fontWeight:900,display:'flex',alignItems:'center',justifyContent:'center'}}>{t}</div>)}</div><div style={{position:'absolute',left:1450,top:220,width:230,height:160,background:P.red,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:38,fontWeight:900,transform:`translate(${mix(p,120,-170)}px,${mix(p,-80,270)}px)`}}>子ども</div><Grain/></AbsoluteFill>;return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={80} text={visual==='second-transition'?'第二の人口転換':visual==='life-stage-option'?'人生の「次」から、人生の「一つ」へ':'人生のメニューが増えすぎた'} size={56}/>{opts.map((t,i)=>{const a=(i/opts.length)*Math.PI*2;const r=330+(i%3)*55;const x=960+Math.cos(a)*r-90;const y=510+Math.sin(a)*r-36;return <Box key={t} x={x} y={y} w={180} h={72} text={t} accent={t==='子ども'}/>})}<Person x={960} y={590} s={1.45}/><Grain/></AbsoluteFill>};

const Housing=({visual,p}:{visual:string;p:number})=>{if(visual==='housing-space') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={95} text="赤ちゃんはクラウドに保存できない" size={58}/><Label x={1120} y={220} text="☁" size={220} color={P.blue}/><Label x={1330} y={460} text="×" size={120} color={P.red}/><Person x={650} y={760} s={1.2} child/><Grain/></AbsoluteFill>;if(visual==='floorplan-grow'||visual==='family-3ldk') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={80} text="HOUSING / FLOOR PLAN" size={30} color={P.muted}/><div style={{position:'absolute',left:160,top:200,width:520,height:570,border:`5px solid ${P.line}`}}><Label x={150} y={230} text="1LDK" size={64}/></div><div style={{position:'absolute',right:160,top:160,width:900,height:650,border:`5px solid ${P.line}`,display:'grid',gridTemplateColumns:'1.2fr 1fr',gridTemplateRows:'1fr 1fr'}}>{Array.from({length:4}).map((_,i)=><div key={i} style={{border:`2px solid ${P.line}`,position:'relative'}}>{i===0&&<Label x={120} y={120} text="3LDK" size={70}/>}</div>)}</div><Label x={815} y={440} text="→" size={95} color={P.gold}/>{visual==='family-3ldk'&&<Label x={1180} y={825} text="値段もファミリー向け" size={40} color={P.gold}/>}<Grain/></AbsoluteFill>;return <AbsoluteFill style={{background:P.bg}}><Box x={290} y={220} w={560} h={520} text="支出が増える"/><Box x={1070} y={220} w={560} h={520} text="家も大きくなる" accent/><Label x={900} y={420} text="＋" size={110} color={P.red}/><Label x={560} y={780} text="資本主義からの、ささやかな祝福" size={50}/><Grain/></AbsoluteFill>};

const Social=({visual,p}:{visual:string;p:number})=>{if(visual==='bed-social') return <AbsoluteFill style={{background:'linear-gradient(180deg,#100e18,#06070b)'}}><div style={{position:'absolute',left:160,top:650,width:1120,height:190,borderRadius:'100px 100px 20px 20px',background:'#252333'}}/><Person x={650} y={650} s={1.25}/><div style={{position:'absolute',left:1040,top:250,width:270,height:430,border:'6px solid #515b67',borderRadius:40,background:'#171b24',transform:`rotate(${mix(p,-12,-5)}deg)`}}><div style={{position:'absolute',inset:18,display:'grid',gridTemplateRows:'repeat(4,1fr)',gap:10}}>{['朝食','木のおもちゃ','自然体験','家族旅行'].map((t,i)=><div key={t} style={{background:'#ddd8cd',color:'#111318',padding:14,fontSize:21,opacity:clamp(p*2-i*.1)}}>{t}</div>)}</div></div><Label x={150} y={85} text="23:00 / FEED" size={26} color={P.muted}/><Grain/></AbsoluteFill>;if(visual==='perfect-feed'||visual==='comparison-grid') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={80} text={visual==='perfect-feed'?'完璧な育児だけが流れてくる':'比較対象：日本中の上位だけ'} size={58}/><div style={{position:'absolute',left:180,top:220,width:1560,height:570,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gridTemplateRows:'repeat(2,1fr)',gap:18}}>{Array.from({length:8}).map((_,i)=><div key={i} style={{background:'#ddd8cd',color:'#111318',padding:18,opacity:clamp(p*2-i*.05),transform:`translateY(${(1-p)*45}px)`}}><div style={{height:145,background:[P.green,P.gold,P.blue,P.violet][i%4],opacity:.55}}/><div style={{fontSize:22,fontWeight:900,marginTop:14}}>{['手作り朝食','知育','自然体験','家族旅行'][i%4]}</div><div style={{fontSize:17,marginTop:8}}>#丁寧な暮らし　#育児</div></div>)}</div><Grain/></AbsoluteFill>;if(visual==='question-shift') return <AbsoluteFill style={{background:P.bg}}><Box x={170} y={310} w={650} h={300} text="子どもを持てるか？"/><Box x={1050} y={260} w={700} h={400} text={'理想的に\n育てられるか？'} accent/><Label x={900} y={410} text="→" size={100} color={P.red}/><Grain/></AbsoluteFill>;if(visual==='wait-more') return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={85} text="『もう少し』は、なかなか来ない" size={60}/>{['貯金','仕事','広い家','余裕'].map((t,i)=><Box key={t} x={220+i*390} y={330} w={300} h={260} text={t} accent={i===3}/>) }<Grain/></AbsoluteFill>;return <AbsoluteFill style={{background:P.bg}}><div style={{position:'absolute',left:570,top:170,width:780,height:610,border:`4px solid ${P.line}`,background:'#11161d'}}><Label x={230} y={70} text="親 採用面接" size={62}/><Person x={390} y={500} s={1.4}/><Box x={500} y={210} w={180} h={190} text="面接官"/><Label x={120} y={450} text="まだ子どもはいない" size={34} color={P.muted}/></div><Grain/></AbsoluteFill>};

const Policy=({visual,p}:{visual:string;p:number})=>{if(visual==='bad-policy') return <AbsoluteFill style={{background:'#0b0909'}}><Label x={150} y={100} text="では、国民を貧しくすればいい？" size={62}/><Label x={780} y={250} text="×" size={300} color={P.red}/><Label x={500} y={760} text="少子化対策史上、最悪の政策" size={52}/><Grain/></AbsoluteFill>;if(visual==='country-differences'){const vals=[.8,1.1,1.3,1.6,1.8];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={85} text="同じ『豊かな国』でも違う" size={58}/>{vals.map((v,i)=><div key={i} style={{position:'absolute',left:260+i*300,top:730-v*240,width:180,height:v*240,background:[P.red,P.violet,P.blue,P.green,P.gold][i],opacity:.75}}><div style={{position:'absolute',top:-45,width:'100%',textAlign:'center',fontSize:28,color:P.paper}}>{v.toFixed(1)}</div></div>)}<Grain/></AbsoluteFill>}if(visual==='old-system') return <AbsoluteFill style={{background:P.bg}}><Box x={220} y={210} w={620} h={560} text={'社会\n2026\n共働き・デジタル'} accent/><Box x={1080} y={210} w={620} h={560} text={'子育て制度\n古い前提\n古い役割分担'}/><Label x={900} y={400} text="≠" size={100} color={P.red}/><Grain/></AbsoluteFill>;if(visual==='contradiction-board'){const req=['働いて','昇進して','自己実現して','育児して','残業して','最高の教育も'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={85} text="社会からの同時要求" size={58}/>{req.map((t,i)=><Box key={t} x={220+(i%3)*510} y={250+Math.floor(i/3)*240} w={430} h={170} text={t} accent={i>2}/>) }<Grain/></AbsoluteFill>}return <AbsoluteFill style={{background:P.bg}}><div style={{position:'absolute',left:520,top:140,width:880,height:720,background:'#e5dfd3',color:'#111318',padding:60,boxSizing:'border-box',transform:`rotate(${mix(p,-4,1)}deg)`}}><div style={{fontSize:56,fontWeight:900,borderBottom:'4px solid #111',paddingBottom:28}}>社会要求 就業規則</div>{['仕事を続けること','育児をすること','教育を最大化すること','住宅費は自己責任','精神的余裕も保つこと'].map((t,i)=><div key={t} style={{fontSize:32,marginTop:42}}>第{i+1}条　{t}</div>)}</div><Grain/></AbsoluteFill>};

const Park=({visual,p}:{visual:string;p:number})=>{if(visual==='project-child') return <AbsoluteFill style={{background:P.bg}}><Box x={150} y={230} w={670} h={520} text="生活の一部"/><Box x={1100} y={180} w={680} h={620} text="巨大プロジェクト" accent/><Label x={900} y={420} text="→" size={100} color={P.red}/><Grain/></AbsoluteFill>;if(visual==='perfect-project'){const labels=['良い学校','良い経験','良い環境','良い関係','良い精神状態','良い将来'];return <AbsoluteFill style={{background:P.bg}}><Person x={960} y={590} s={1.45} child/>{labels.map((t,i)=>{const a=-Math.PI/2+(i/labels.length)*Math.PI*2;const x=960+Math.cos(a)*350-110;const y=500+Math.sin(a)*290-45;return <Box key={t} x={x} y={y} w={220} h={90} text={t} accent={i===5}/>})}<Grain/></AbsoluteFill>}return <AbsoluteFill style={{background:'linear-gradient(180deg,#1c2a34 0 48%,#172318 48%)'}}><div style={{position:'absolute',left:0,right:0,top:540,height:7,background:'#52664e'}}/>{Array.from({length:7}).map((_,i)=><div key={i} style={{position:'absolute',left:120+i*280,top:300+(i%2)*25,width:45,height:270,background:'#3b332b'}}><div style={{position:'absolute',left:-90,top:-100,width:220,height:190,borderRadius:'50%',background:'#2f4d34'}}/></div>)}<Person x={610} y={790} s={1.3}/><Person x={760} y={790} s={1.35}/><Person x={1220+Math.sin(p*Math.PI*2)*90} y={720} s={1.0} child/><Person x={1450} y={720} s={1.15}/>{visual==='want-but-afraid'&&<><Label x={230} y={150} text="欲しいとは思う。" size={56}/><Label x={1180} y={150} text="でも、怖い。" size={56} color={P.gold}/></>}<Grain/></AbsoluteFill>};

const Finale=({visual,p}:{visual:string;p:number})=>{if(visual==='historical-progress'){const labels=['生存','学校','権利','心','可能性'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={90} text="子どもを大切にする歴史" size={58}/>{labels.map((t,i)=><div key={t} style={{position:'absolute',left:180+i*340,top:650-i*90,width:280,height:150,border:`2px solid ${P.line}`,background:P.panel,display:'flex',alignItems:'center',justifyContent:'center',fontSize:38,color:i===4?P.gold:P.paper}}>{t}</div>)}<Grain/></AbsoluteFill>}if(visual==='requirement-wall'||visual==='invisible-bill'){const labels=['家','収入','時間','精神的余裕','教育環境','夫婦関係','仕事','個性尊重'];return <AbsoluteFill style={{background:P.bg}}><Label x={150} y={85} text={visual==='invisible-bill'?'見えない請求書':'親になるための要求条件'} size={58}/>{labels.map((t,i)=><Box key={t} x={180+(i%4)*405} y={230+Math.floor(i/4)*270} w={330} h={200} text={t} accent={i%3===0}/>) }<Grain/></AbsoluteFill>}if(visual==='luxury-definition'||visual==='perfect-parenting') return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 45%,#271f17,#090b10 70%)'}}><div style={{position:'absolute',left:550,top:160,width:820,height:650,border:'4px solid #6b5835',background:'#14100c',display:'flex',alignItems:'center',justifyContent:'center'}}><Person x={410} y={470} s={1.5} child/></div><Label x={360} y={820} text={visual==='perfect-parenting'?'贅沢品になったのは「完璧な子育て」':'子どもそのものが高級品なのではない'} size={50} color={P.gold}/><Grain/></AbsoluteFill>;if(visual==='care-paradox'||visual==='too-precious') return <AbsoluteFill style={{background:P.bg}}><Box x={220} y={190} w={650} h={590} text="もっと大切に"/><Label x={430} y={330} text="♥" size={180} color={P.red}/><Box x={1050} y={190} w={650} h={590} text="もっと高くなる" accent/><Label x={1280} y={320} text="¥" size={190}/><Label x={910} y={420} text="→" size={100} color={P.gold}/><Grain/></AbsoluteFill>;if(visual==='final-thesis') return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 50%,#222936,#090b10 72%)'}}><Label x={330} y={180} text="豊かになったことで" size={60}/><Label x={310} y={300} text="一人に求めるものまで" size={64}/><Label x={500} y={435} text="豊かになりすぎた" size={82} color={P.gold}/><Label x={580} y={650} text="MONEY / TIME / CAREER / HOME / EDUCATION / LOVE" size={28} color={P.muted}/><Grain/></AbsoluteFill>;return <Apartment visual="final-room-dark" p={p}/>};

export const SceneArt=({visual,p}:{visual:string;p:number})=>{
  if(['apartment-tour','child-room','storage-joke','return-room','final-room-dark'].includes(visual)) return <Apartment visual={visual} p={p}/>;
  if(['cost-cloud','search-cost','excel-humanity'].includes(visual)) return <CostScene visual={visual} p={p}/>;
  if(['paradox-intro','title-question'].includes(visual)) return <Paradox visual={visual} p={p}/>;
  if(['fertility-chart','modern-home','appliance-parade','money-explanation','price-transformation'].includes(visual)) return <DataScene visual={visual} p={p}/>;
  if(['becker-portrait','resource-pie','quantity-quality','investment-stack'].includes(visual)) return <Becker visual={visual} p={p}/>;
  if(visual==='car-analogy') return <Car p={p}/>;
  if(['parent-job-wheel','corporate-parent','cafe-friend','everyone-does-it','parent-arms-race','six-year-old-exam','intensive-parenting','bar-raised'].includes(visual)) return <Parenting visual={visual} p={p}/>;
  if(['office-woman','career-ladder','opportunity-cost','full-life','child-penalty','nursery-call','capitalism-joke'].includes(visual)) return <Office visual={visual} p={p}/>;
  if(['life-menu','choice-explosion','second-transition','life-stage-option','tetris-life'].includes(visual)) return <Life visual={visual} p={p}/>;
  if(['housing-space','floorplan-grow','family-3ldk','capitalism-blessing'].includes(visual)) return <Housing visual={visual} p={p}/>;
  if(['bed-social','perfect-feed','comparison-grid','question-shift','wait-more','parent-interview'].includes(visual)) return <Social visual={visual} p={p}/>;
  if(['bad-policy','country-differences','old-system','contradiction-board','rulebook-joke'].includes(visual)) return <Policy visual={visual} p={p}/>;
  if(['park-family','want-but-afraid','project-child','perfect-project'].includes(visual)) return <Park visual={visual} p={p}/>;
  if(['historical-progress','requirement-wall','luxury-definition','perfect-parenting','care-paradox','too-precious','invisible-bill','final-thesis'].includes(visual)) return <Finale visual={visual} p={p}/>;
  return <AbsoluteFill style={{background:P.bg}}><Label x={470} y={440} text="豊かさの、見えない請求書" size={72}/><Grain/></AbsoluteFill>;
};
